config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :outfits do
    resources :outfit_products, only: [:new, :create]
    member do
      get "change"
    end
    collection do
      get 'new_from_products'  # Route to display the form for creating an outfit from products
      post 'create_from_products'  # Add a POST route for the create_from_products actio
    end
  end
  resources :outfit_products, only: [:destroy]
  resources :outfit_products, only: :update, defaults: { format: :json }

  resources :products, only: [:create, :show] do
    resources :closet_items, only: [:create, :destroy]
  end
end

app/views/pages/home.html.erb
<div class="home-container">
  <!-- Title and Buttons Section -->
  <%= image_tag "what_to_wear_logo.png", alt: "App Logo", class: "home-logo mt-3" %>
  <div class="title-buttons-container">
    <h1 id="home-title" class="title-home">
      <span>WHAT</span>
      <span>DO</span>
      <span>I</span>
      <span>WEAR</span>
    </h1>
    <!-- Fashion at Your Fingertips paragraph with wrapping -->
    <!-- Buttons, centered -->
    <div class="buttons-home">
      <%= link_to new_outfit_path, class: "btn-home upload-btn", style: "text-decoration: none;" do %>
        <i class="fa-solid fa-wand-magic-sparkles"></i> Find outfit
      <% end %>
    </div>
    <p class="responsive-text"> Snap a Pic and Find the Fit. Use AI to Put Together Outfits. Build Your Style.</p>
  </div>
</div>